# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy build to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
     **/*.jar
     
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeededOrFailed()
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeededOrFailed()

