# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeededOrFailed()

